export const emptyIssue = {
  fields: {
    components: [],
    statuscategorychangedate: '',
    workratio: -1,
    assignee: null,
    aggregatetimeoriginalestimate: null,
    status: {
      id: '10000',
      iconUrl: 'https://sesame-team-pfe.atlassian.net/',
      description: '',
      self: 'https://sesame-team-pfe.atlassian.net/rest/api/2/status/10000',
      name: 'À faire',
      statusCategory: {
        key: 'new',
        self: 'https://sesame-team-pfe.atlassian.net/rest/api/2/statuscategory/2',
        colorName: 'blue-gray',
        name: 'A faire',
        id: 2,
      },
    },
    aggregatetimespent: null,
    watches: {
      isWatching: false,
      watchCount: 0,
      self: 'https://sesame-team-pfe.atlassian.net/rest/api/2/issue/SCRUM-2/watchers',
    },
    reporter: {
      self: '',
      emailAddress: '',
      accountType: '',
      accountId: '',
      timeZone: '',
      active: true,
      displayName: '',
    },
    timespent: null,
    customfield_10001: null,
    resolution: null,
    labels: [],
    progress: {
      total: 0,
      progress: 0,
    },
    aggregateprogress: {
      total: 0,
      progress: 0,
    },
    resolutiondate: null,
    environment: null,
    duedate: '',
    votes: {
      self: '',
      hasVoted: false,
      votes: 0,
    },
    customfield_10020: null,
    security: null,
    description: null,
    customfield_10021: null,
    issuelinks: [],
    subtasks: [],
    created: '',
    lastViewed: '',
    creator: {
      displayName: '',
      timeZone: '',
      accountType: '',
      active: true,
      emailAddress: '',
      self: '',
      accountId: '',
    },
    timeoriginalestimate: null,
    fixVersions: [],
    summary: '',
    updated: '',
    issuetype: {
      id: '',
      hierarchyLevel: 0,
      iconUrl: '',
      avatarId: '',
      subtask: false,
      description: '',
      entityId: '',
      name: '',
      self: '',
    },
    aggregatetimeestimate: null,
    customfield_10016: null,
    customfield_10015: '',
    customfield_10032: null,
    customfield_10019: '0|i00007:',
    project: {
      name: '',
      simplified: true,
      id: '',
      key: '',
      projectTypeKey: '',
      self: '',
    },
    statusCategory: {
      key: 'new',
      self: 'https://sesame-team-pfe.atlassian.net/rest/api/2/statuscategory/2',
      colorName: 'blue-gray',
      name: 'A faire',
      id: 2,
    },
    versions: [],
    timeestimate: null,
    priority: {
      id: '3',
      name: 'Medium',
      iconUrl: 'https://sesame-team-pfe.atlassian.net/images/icons/priorities/medium.svg',
      self: 'https://sesame-team-pfe.atlassian.net/rest/api/2/priority/3',
    },
  },
  id: '',
  key: 'interne',
  self: '',
  configId: '',
  expand: 'operations,versionedRepresentations,editmeta,changelog,renderedFields',
}
